# Use postgres/example user/password credentials
services:
  db:
    image: postgres
    container_name: dev_postgres_ai_text
    hostname: dev_postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 127.0.0.1:5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
